## Numpy

  

In [3]:
import numpy as np        

## Creating List

In [4]:
Mylist= [1,2,3]
array_obt = np.array(Mylist)
array_obt

array([1, 2, 3])

In [5]:
array_di = np.array([5,4,5])
array_di

array([1, 2, 3])

In [6]:
array_mat = np.array([[1,2,3],[4,5,6]])
array_mat
                      

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array_mat.shape

(2, 3)

In [9]:
list_con = np.arange(0,30,2)
list_con

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [11]:
list_con = list_con.reshape(5,3)
list_con

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [12]:
list_div_in = np.linspace(0,4,9)
list_div_in

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [13]:
list_div_in.resize(3,3)
list_div_in

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [16]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.diag(Mylist)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [24]:
p= np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
api_hor = np.hstack([p,2*p])
api_hor

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [27]:
api_ver = np.vstack([p,2*p])
api_ver

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

## Operation

In [28]:
array_obt+array_di

array([2, 4, 6])

In [29]:
array_obt * array_di

array([1, 4, 9])

In [30]:
array_obt ** 2

array([1, 4, 9])

## Producto punto usual.

In [31]:
array_di.dot(array_obt)

14

In [34]:
matri = np.array([array_di, array_di**2])
matri

array([[1, 2, 3],
       [1, 4, 9]])

In [35]:
matri.shape

(2, 3)

In [36]:
matri.T

array([[1, 1],
       [2, 4],
       [3, 9]])

In [37]:
matri.T.shape

(3, 2)

In [38]:
matri.dtype

dtype('int64')

In [39]:
matri.astype('f')

array([[1., 2., 3.],
       [1., 4., 9.]], dtype=float32)

In [41]:
a = np.array([-5,-2,-1,1,2,3,5,6])
a

array([-5, -2, -1,  1,  2,  3,  5,  6])

In [42]:
a.sum()

9

In [43]:
a.min()

-5

In [44]:
a.max()

6

In [45]:
a.mean()

1.125

In [46]:
a.std()

3.4437443284889775

In [47]:
a.argmax()

7

In [48]:
a.argmin()

0

## Indexing/slicing

In [49]:
ma = np.arange(13)**2
ma

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [50]:
ma[0],ma[1], ma[0:3]

(0, 1, array([0, 1, 4]))

In [51]:
ma[0:5]

array([ 0,  1,  4,  9, 16])

In [52]:
ma[-4:]

array([ 81, 100, 121, 144])

In [53]:
ma[-5::-2]

array([64, 36, 16,  4,  0])

In [54]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [55]:
r[2,2]

14

In [56]:
r[2,0:3]

array([12, 13, 14])

In [57]:
r[:5,1:]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [58]:
r[r>30]

array([31, 32, 33, 34, 35])

In [60]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [61]:
r2= r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [63]:
r2[:,:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [64]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [65]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [66]:
r_copy[:,:]=10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterating over matriz

In [68]:
randomm = np.random.randint(0,10,(5,5))
randomm

array([[4, 5, 5, 9, 5],
       [5, 5, 8, 4, 1],
       [4, 1, 2, 1, 4],
       [5, 6, 4, 3, 5],
       [8, 3, 6, 4, 1]])

In [69]:
for row in randomm:
    print(row)

[4 5 5 9 5]
[5 5 8 4 1]
[4 1 2 1 4]
[5 6 4 3 5]
[8 3 6 4 1]


In [71]:
for i in range(len(randomm)):
    print(randomm[i])

[4 5 5 9 5]
[5 5 8 4 1]
[4 1 2 1 4]
[5 6 4 3 5]
[8 3 6 4 1]


In [72]:
for i, row in enumerate(randomm):
    print("row",i,'is',row)

row 0 is [4 5 5 9 5]
row 1 is [5 5 8 4 1]
row 2 is [4 1 2 1 4]
row 3 is [5 6 4 3 5]
row 4 is [8 3 6 4 1]


In [74]:
test2 = randomm**2
test2

array([[16, 25, 25, 81, 25],
       [25, 25, 64, 16,  1],
       [16,  1,  4,  1, 16],
       [25, 36, 16,  9, 25],
       [64,  9, 36, 16,  1]])

In [75]:
for i,j in zip(randomm,test2):
    print(i,'+',j,'=',i+j)

[4 5 5 9 5] + [16 25 25 81 25] = [20 30 30 90 30]
[5 5 8 4 1] + [25 25 64 16  1] = [30 30 72 20  2]
[4 1 2 1 4] + [16  1  4  1 16] = [20  2  6  2 20]
[5 6 4 3 5] + [25 36 16  9 25] = [30 42 20 12 30]
[8 3 6 4 1] + [64  9 36 16  1] = [72 12 42 20  2]


In [77]:
[2,3]+[2,1]

[2, 3, 2, 1]

In [78]:
type(lambda x:x)

function

In [79]:
question = np.arange(36)
question

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [80]:
question.resize(6,6)
question

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [81]:
question[::7]

array([[0, 1, 2, 3, 4, 5]])

In [83]:
question[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [84]:
question.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])